<?php echo $this->plugin('doctype') ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>PHPNW11 Tutorial</title>
  <?php echo $this->plugin('headLink')->appendStylesheet('/css/site.css') ?>
</head>
<body>
<div id="header">
    <div id="header-logo">
        <a href="<?php echo $this->plugin('url')->direct(array('controller' => 'index', 'action' => 'index'), array('name' => 'home')) ?>">
            PHPNW11 Tutorial</a>
    </div>
    <div id="header-navigation">
        <a href="<?php echo $this->plugin('url')->direct(
            array('controller'=>'index', 'action' => 'index'),
            array('name' => 'default')) ?>">Home</a>
        |
        <a href="<?php echo $this->plugin('url')->direct(
            array('module'=>'album', 'controller'=>'index', 'action' => 'index'),
            array('name' => 'default')) ?>">Albums</a>
    </div>
</div>

<?php 
    // $this->vars() in the layout isn't the same $this->vars() that's in the view script.
    echo $this->vars()->getRawValue('content');
?>

</body>
</html>
