<?php echo $this->doctype()->setDoctype('HTML5'); ?>

<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
  <title><?php echo isset($title) ? $this->vars()->escape($title) . ' - ' : ''; ?>PHPNW11 Tutorial</title>
  <?php echo $this->headLink()->appendStylesheet('/css/site.css') ?>

</head>
<body>
<div id="header">
    <div id="header-logo">
        <a href="<?php echo $this->url(array(), 
            array('name' => 'home')) ?>">
            PHPNW11 Tutorial</a>
    </div>
    <div id="header-navigation">
        <a href="<?php echo $this->url(
            array(),
            array('name' => 'home')) ?>">Home</a>
        |
        <a href="<?php echo $this->url(
            array('controller'=>'album', 'action' => 'index'),
            array('name' => 'default')) ?>">Albums</a>
    </div>
</div>

<?php 
    // $this->vars() in the layout isn't the same $this->vars() that's in the view script.
    echo $this->vars()->getRawValue('content');
?>

</body>
</html>
