<?php 
$vars = $this->vars();
extract($this->vars()->getArrayCopy()); ?>

<h1><?php echo $title;?></h1>
<p><?php echo $content ;?></p>

<p><a href="<?php echo $this->plugin('url')->direct(array('controller'=>'album', 
        'action'=>'add'), array('name' => 'default'));?>">Add new album</a></p>

<table>
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($albums as $album) : ?>
<tr>
    <td><?php echo $vars->escape($album->title);?></td>
    <td><?php echo $vars->escape($album->artist);?></td>
    <td>
        <a href="<?php echo $this->plugin('url')->direct(array('controller'=>'album', 
            'action'=>'edit', 'id'=>$album->id), array('name' => 'default'));?>">Edit</a>
        <a href="<?php echo $this->plugin('url')->direct(array('controller'=>'album', 
            'action'=>'delete', 'id'=>$album->id), array('name' => 'default'));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>